apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          image: prestashop/prestashop:1.7
          env:
            - name: DB_SERVER
              value: mysql
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: prestashop-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 80
