apiVersion: v1
kind: Secret
metadata:
  name: prestashop-secret
type: Opaque
data:
  DB_USER: c3VwcGluZm8= # Encoded value of "supinfo"
  DB_PASSWORD: UEFuYW1ib3NzNzVBQEA= # Encoded value of "PAnamboss75A@"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c3VwcGluZm8= # Encoded value of "supinfo"
  MYSQL_DATABASE: c3VwaW5mb2Ri # Encoded value of "supinfodb"
  MYSQL_USER: c3VwaW5mbw== # Encoded value of "supinfo"
  MYSQL_PASSWORD: UEFuYW1ib3NzNzVBQEA= # Encoded value of "PAnamboss75A@"
